### ISSUE TITLE
Optimize checksumming

### ISSUE THREAD

**Issue by RPDiep** [RPDiep/aur-spotify#3]
https://github.com/RPDiep/aur-spotify/blob/master/generator/pkgbuild_generator.py#L98-L101
This fits the entire file in memory and thus isn't memory efficient. 
This could be done either with a temp file or read in chunks.
Saw an example on https://stackoverflow.com/questions/3431825/generating-an-md5-checksum-of-a-file

**Comment by kvij** [comment]
Agreed I thought that 100 MiB would not be a problem on most developers systems but will fix it this weekend. If at all possible I want to avoid writing to disk so the chunk option sounds nice.
